### PR TITLE
Floating window support and cleaning up some background behavior

### PR DESCRIPTION
**Pull request by dhk2**

### CODE REVIEW

**Comment by sschueller** [comment]
Thank you, I will go over it on the weekend.

**Comment by dhk2** [comment]
Great, I see a lot of cleaning up I can do before that.

**Comment by dhk2** [comment]
There are some definite issues with how the preferences are working. I tried several different ways but could not get the warning alerts to fire reliably, and the currently existing one for themes has the same problem. I took the PIP warnings out for now, and think upgrading to the androidx.preference library may be the best solution overall

**Comment by sschueller** [comment]
Yes, there is also the theme issue on first load. I will see if I can update the prefs.

**Comment by sschueller** [comment]
Very cool, thank you.

**Pull request merged**
