### PR TITLE
Add stop button to expanded notification, and stop and switch to audio in video window

### PR DESCRIPTION
**Pull request by dhk2**
could probably use a better icon for switch to background audio

### CODE REVIEW

**Comment by sschueller** [comment]
Thanks for implementing this. Can you resolve the merge conflict by merging the ```develop``` branch into yours?

**Comment by dhk2** [comment]
No idea what the problem was, moving the new code to separate functions and moving them to the top instead of the bottom seems to have allayed whatever issue git was having.

**Comment by dhk2** [comment]
Looks like play and pause are working properly now in floating mode

**Comment by sschueller** [comment]
Thanks

**Pull request merged**
